# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/sda2/alex/Games/EliteTools/edmcoverlay2_myedits

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alex/Games/EliteTools/edmcoverlay2_myedits

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Games/EliteTools/edmcoverlay2_myedits/CMakeFiles /home/alex/Games/EliteTools/edmcoverlay2_myedits//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alex/Games/EliteTools/edmcoverlay2_myedits/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named overlay

# Build rule for target.
overlay: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 overlay
.PHONY : overlay

# fast build rule for target.
overlay/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/build
.PHONY : overlay/fast

json_message.o: json_message.cc.o
.PHONY : json_message.o

# target to build an object file
json_message.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/json_message.cc.o
.PHONY : json_message.cc.o

json_message.i: json_message.cc.i
.PHONY : json_message.i

# target to preprocess a source file
json_message.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/json_message.cc.i
.PHONY : json_message.cc.i

json_message.s: json_message.cc.s
.PHONY : json_message.s

# target to generate assembly for a file
json_message.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/json_message.cc.s
.PHONY : json_message.cc.s

overlay.o: overlay.cpp.o
.PHONY : overlay.o

# target to build an object file
overlay.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/overlay.cpp.o
.PHONY : overlay.cpp.o

overlay.i: overlay.cpp.i
.PHONY : overlay.i

# target to preprocess a source file
overlay.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/overlay.cpp.i
.PHONY : overlay.cpp.i

overlay.s: overlay.cpp.s
.PHONY : overlay.s

# target to generate assembly for a file
overlay.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/overlay.cpp.s
.PHONY : overlay.cpp.s

socket.o: socket.cc.o
.PHONY : socket.o

# target to build an object file
socket.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/socket.cc.o
.PHONY : socket.cc.o

socket.i: socket.cc.i
.PHONY : socket.i

# target to preprocess a source file
socket.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/socket.cc.i
.PHONY : socket.cc.i

socket.s: socket.cc.s
.PHONY : socket.s

# target to generate assembly for a file
socket.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/socket.cc.s
.PHONY : socket.cc.s

xoverlayoutput.o: xoverlayoutput.cpp.o
.PHONY : xoverlayoutput.o

# target to build an object file
xoverlayoutput.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/xoverlayoutput.cpp.o
.PHONY : xoverlayoutput.cpp.o

xoverlayoutput.i: xoverlayoutput.cpp.i
.PHONY : xoverlayoutput.i

# target to preprocess a source file
xoverlayoutput.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/xoverlayoutput.cpp.i
.PHONY : xoverlayoutput.cpp.i

xoverlayoutput.s: xoverlayoutput.cpp.s
.PHONY : xoverlayoutput.s

# target to generate assembly for a file
xoverlayoutput.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/overlay.dir/build.make CMakeFiles/overlay.dir/xoverlayoutput.cpp.s
.PHONY : xoverlayoutput.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... overlay"
	@echo "... json_message.o"
	@echo "... json_message.i"
	@echo "... json_message.s"
	@echo "... overlay.o"
	@echo "... overlay.i"
	@echo "... overlay.s"
	@echo "... socket.o"
	@echo "... socket.i"
	@echo "... socket.s"
	@echo "... xoverlayoutput.o"
	@echo "... xoverlayoutput.i"
	@echo "... xoverlayoutput.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

