#!/usr/bin/env python3

"""Helper script which allows to make keybinding into OS which will turn off/on overlay. Should be used outside EDMC."""

import json
import socket
import errno
import time
import random
import sys


def _send_raw_text(inpstr: str):
    inpstr = inpstr.replace("\\u202f", "\\u00a0")
    bstr = inpstr.encode("utf-8")
    for retries in range(1, 7):
        try:
            conn = socket.socket()
            conn.connect(("127.0.0.1", 5010))
            conn.send(str(len(bstr)).encode("utf-8") + b"#" + bstr)
            conn.close()
            break
        except socket.error as e:
            if e.errno == errno.ECONNREFUSED:
                time.sleep(random.randint(200, 450) / 1000.0)
            else:
                raise
    return None


def send_command(command: str):
    _send_raw_text(json.dumps({"command": command}))


if len(sys.argv) > 1:
    send_command(sys.argv[1])
else:
    print("{} <overlay_on | overlay_off>".format(sys.argv[0]))
